### ISSUE TITLE
Gesture Menu Bug :(

### ISSUE THREAD

**Issue by Mosaty** [ZionDevelopers/gesturemenu#3]
Hi everyone ,
Today i have a problem :(
When I'm connect to a server with gesture Menu , a windows spawn
http://www.noelshack.com/2015-32-1438623444-sans-titre-1.jpg
And when i click on the cross for close the windows an other spawn all of time , i can't play on this server :( please found this error and patch that please

Thank for reading
bye

**Comment by juliocoliveira** [comment]
that is not my addon.
